### ISSUE TITLE
Confusion about compatibility

### ISSUE THREAD

**Issue by matthewp** [webcomponents/shadycss#1]
I find this in the readme to be unclear:

> If native ShadowDOM is available, no scoping will be applied.

What I'm wondering is, if native ShadowDOM is available, will shadycss' `@apply` work within that native shadowDOM? Or does `@apply` only work with shadydom (meaning it shouldn't be used in browsers that support ShadowDOM)?

I imagine it *does* work with native ShadowDOM, but the sentence confused me.

**Comment by azakus** [comment]
`@apply` shim works with both shady and shadow dom. The README needs some updating to clarify that :)

**Comment by azakus** [comment]
Should be much clearer in 668a962

**Comment by matthewp** [comment]
Awesome, thanks so much.
