### ISSUE TITLE
Shim dynamically inserted <style>s?

### ISSUE THREAD

**Issue by darrylyeo** [webcomponents/shadycss#105]
I have a custom element where at runtime I need to inject a `<style>` element (that doesn't come from within a `<template>`) into the shadow DOM. This does not get shimmed but instead stays inside the simulated Shady DOM, unprocessed.

Example:

```
const USING_SHADY_CSS = 'ShadyCSS' in window && !ShadyCSS.nativeShadow

const MyElement = class extends HTMLElement {
	connectedCallback(){
		const root = this.attachShadow({mode: 'open'})

		const template = $('#my-template')

		if(USING_SHADY_CSS){
			ShadyCSS.prepareTemplate($template, 'my-element')
		}

		const additionalStyle = document.createElement('style')
		additionalStyle.textContent = ':host > .foo { color: red }'
		root.appendChild(additionalStyle)

		root.appendChild(document.importNode(template.content))
	}
}
customElements.define('my-element', MyElement)
```

Is there a right way to get ScopingShim to process it? If not, can there be a way to automatically detect style injections and correctly scope them?

**Comment by azakus** [comment]
Deduplicated against #134
