### ISSUE TITLE
no replacement for `scopeSubtree` method

### ISSUE THREAD

**Issue by gurpreetatwal** [webcomponents/shadycss#114]
The [Polymer 2.0 docs](https://www.polymer-project.org/2.0/docs/api/mixins/Polymer.LegacyElementMixin#method-scopeSubtree) state that this shim provides a `scopeSubtree` method, but after much digging I have not been able to find such a method in the latest version of the shim.

However I'm not 100% sure if that exact method is the one I even need. 

I have a Polymer element that encapsulates another JavaScript library (which dynamically inserts and updates content) and thus I have been unable to style any of the elements created by that library because the lack the 'scoping' class which polymer/shadycss tack on to my styles.

**Comment by azakus** [comment]
This process should be automatic now, as ShadyCSS uses a MutationObserver to notice added and removed elements and shim them.

**Comment by gurpreetatwal** [comment]
Ah oops, I had actually found the answer to my question the next day but forgot about this issue. 

Should the docs be update to say something along the lines of your comment? The only way I was able to reach the same conclusion as your comment was by reading through a solid chunk of the ShadyCss code, ending up spending a solid couple of hours on the issue.
