### ISSUE TITLE
:nth-of-type(3n+1) CSS rule rewritten as .tag-name:nth-of-type(3n+1).tag-name

### ISSUE THREAD

**Issue by keanulee** [webcomponents/shadycss#121]
The `.tag-name` class selector is added twice which messes with precedence.

Repro: the first date card on https://summit.polymer-project.org/schedule with non-shadow DOM browser (e.g. Firefox) when the number of columns is even.

(Will work on a smaller repro later, hopefully before I forget about this bug.)

**Comment by azakus** [comment]
Small repro: http://jsbin.com/cozoreh/edit?html,output

Looks like any `nth-child(n+1)` will do it.
