### ISSUE TITLE
Preserve sourcemap comments

### ISSUE THREAD

**Issue by TimvdLippe** [webcomponents/shadycss#125]
This was originally an issue at https://github.com/Polymer/polymer/issues/2206

ShadyCSS eagerly removes comments https://github.com/webcomponents/shadycss/blob/a6433867ce3fe449372ee89ab1b779b463ff4b9f/src/css-parse.js#L66
but should probably preserve sourcemap comments.

**Comment by azakus** [comment]
I'm not entirely sure this is a good idea. ShadyCSS will rewrite the style in a number of different ways, so the sourcemap will probably not work anyway.
