### ISSUE TITLE
ShadyCSS.styleElement does not work for non-custom elements

### ISSUE THREAD

**Issue by tomalec** [webcomponents/shadycss#128]
I would like to use this polyfill for a regular shadow host (not a custom element class)
http://jsbin.com/hasosi/1/edit?html,output
```html
  <div id="shadow-host"><span>I'll be green</span></div>
  <template id="shadow-dom">
    <style>
      :host{
        background-color: green;        
        color: lightgreen;
      }
      ::slotted(span){
        text-decoration: line-through;
      }
    </style>
    <slot></slot>
    I'm green
  </template>
  
  <script>
    setTimeout(function(){
      const shost = document.querySelector('#shadow-host');
      const sroot = shost.attachShadow({mode: 'open'});
      sroot.appendChild(document.importNode(document.querySelector('#shadow-dom').content, true));
      ShadyCSS && ShadyCSS.styleElement(shost);
    },1000);
  </script>
```

From what I can find in the README, it's 
>a library to simulate ShadowDOM style encapsulation (ScopingShim)

not "a library to simulate custom element's shadow root", so I really hope it's possible to use it to polyfill Shadow DOM style encapsulation for any host.

The [Requirements](https://github.com/webcomponents/shadycss#requirements) does not event require CustomElements

**Comment by azakus** [comment]
It is currently not possible, but I'm working on it!

**Comment by azakus** [comment]
Deduplicated against #134
