### ISSUE TITLE
update min.js

### ISSUE THREAD

**Issue by steventill** [webcomponents/shadycss#129]
when using rails
the comment at the bottom - //# sourcemappingurl=<filename>.js.map
the asset pipeline finds, can you change the comment (remove the #) or just remove it all together when you do builds

**Comment by TimvdLippe** [comment]
This is intended behavior, as we also supply the sourcemap for easier debugging of the polyfill. If you require the removal of comments, we advise you to use a JS minifier that can remove the comments for you.
