### ISSUE TITLE
Outside CSS not reset

### ISSUE THREAD

**Issue by mathieumahe** [webcomponents/shadycss#139]
Hello !

I'm not sure if it's normal but when I try to use ShadyCSS with firefox, the css from outside my template are used to render my template (it's not like that on Chrome and Safari)

Here's a simple exemple on jsbin : http://jsbin.com/maqohoxowu/edit?html,output

The second h2 are not supposed to be dotted, as the css rule is at the top of the file, not in the template.

**Comment by TimvdLippe** [comment]
This is a document limitation of the polyfill: https://github.com/webcomponents/shadycss#document-level-styling-is-not-scoped-by-default As the polyfill doesn't implement full shadow dom, we can not prevent this styling, unless the style tag is processed by ShadyCSS.
