### ISSUE TITLE
ShadyCSS scopes styles of templates, but their content is stamped outside the scope of the dom-module

### ISSUE THREAD

**Issue by valdrinkoshi** [webcomponents/shadycss#17]
I'm stamping template's content into another node, but the ShadyCSS scopes styles to the dom-module.
In this example, I stamp and append a clone of the template into `<body>` after 300ms. 
When forcing ShadyDOM and customElements, the stamped clone won't receive the correct `.target` style
http://jsbin.com/lobuna/22/edit?html,output

**Comment by valdrinkoshi** [comment]
If the element is removed then added again to the document, style is correctly applied
```js
stamp: function() {
  const ctor = templatizer.templatize(this.$.renderer, {});
  const inst = new ctor(this);
  document.body.appendChild(inst.root);
  const clone = document.body.lastChildElement;
  document.body.removeChild(clone);
  document.body.appendChild(clone);        
}
```

**Comment by valdrinkoshi** [comment]
@azakus updated jsbin after our offline discussion. Seems like style scoping update is not triggered for dynamically added elements

**Comment by azakus** [comment]
The dynamic scoping mutation observer only removes scoping for nodes removed from an element, it doesn't check that it needs to remove scoping for added nodes.

Should be a simple fix.
