### ISSUE TITLE
What is ShadyCSS.applyStyle(element) for?

### ISSUE THREAD

**Issue by tuespetre** [webcomponents/shadycss#18]
In the README, it says to use it whenever dynamic updates are required. But what does that *mean*? Dynamic updates to *what*? It sure doesn't work for what I expected it to (applying the 'scoping classes' to dynamically generated elements where needed.)

**Comment by SerkanSipahi** [comment]
e.g. lets say you have many components that use native css variables for background-color, color etc. When christmas is you can use: 
```js
if(christmas){
    ShadyCSS.updateStyles({
       '--background-color', 'red',
       '--font-color', 'white'
    });
}

```

**Comment by tuespetre** [comment]
I understand updateStyles but I am not certain about what I would use applyStyle(element) for.

**Comment by tuespetre** [comment]
I think I've got it. `ShadyCSS.applyStyle(element)` is to ensure that the newly created (or updated) element gets the correct CSS Custom Properties. It's nothing to do with applying the 'scoping classes'. 

Maybe it should be renamed `ShadyCSS.applyProperties(element)`.
