### ISSUE TITLE
window.ShadyCSS.flushCustomStyles is not a function

### ISSUE THREAD

**Issue by super-kamil** [webcomponents/shadycss#180]
![image](https://user-images.githubusercontent.com/708028/39811491-258b4c96-5389-11e8-8673-96b1104a6a85.png)

Hi,

i'm getting this error in 1.2.0 and Chrome 66.

Any ideas?

**Comment by web-padawan** [comment]
See Polymer/polymer#5221

**Comment by azakus** [comment]
My bad, that is new API in v1.2, but Webcomponentsjs v1 doesn't have that API yet. I'll make it conditional for compatibility.

**Comment by azakus** [comment]
Fixed in v1.2.1
