### ISSUE TITLE
:dir() is not transformed correctly with complicated selectors

### ISSUE THREAD

**Issue by azakus** [webcomponents/shadycss#234]
The `:dir()` transform happens after selectors are split into "simple" selectors, without ancestor/descendant/sibling combinators.

However, the output of the `:dir()` transform creates two selectors, and both must contain the whole of the input selector.

Example for x-foo element:
```css
:dir(rtl) > #foo > #bar {}
```
should be
```css
[dir="rtl"] .x-foo > #foo.x-foo > #bar.x-foo, .x-foo[dir="rtl"] > #foo.x-foo > #bar.x-foo {}
```
but is transformed as
```css
[dir="rtl"] .x-foo, .x-foo[dir="rtl"] > #foo.x-foo > #bar.x-foo, .x-foo[dir="rtl"] > #foo.x-foo > #bar.x-foo {}
```

**Comment by sorvell** [comment]
Let's consider this case:

```css
#zot > #hug:dir(rtl) > #foo > #bar {}
```

That should be 

```css 
[dir="rtl"] #zot > #hug.x-foo > #foo.x-foo > #bar.x-foo,
#zot[dir="rtl"] > #hug.x-foo > #foo.x-foo > #bar.x-foo,
#zot.x-foo > #hug[dir="rtl"].x-foo > #foo.x-foo > #bar.x-foo {}
```

In other words, we need a new selector for each compound selector to the left of the `:dir`.
