### ISSUE TITLE
Scoping classes show in innerHTML etc

### ISSUE THREAD

**Issue by treshugart** [webcomponents/shadycss#28]
I included the polyfill in the SkateJS tests and noticed some were failing due to the `style-scope` and class based on the element's `localName` appearing in innerHTML. It would seem these shouldn't expose themselves to consumers since they're side-effects that could screw up virtual DOMs and break the tests of other people's libraries, too.

I could be missing something. Would preventing these from bleeding out cause any issues?

**Comment by azakus** [comment]
Sorry for not responding earlier, but this mechanism is how the scoping emulation of ShadyCSS works. I don't think there is any way to simulate the styling scoping of ShadowDOM without modifying both the stylesheets in the DOM and the elements that styling is supposed to apply to.

Even simulating the encapsulation with inline styles would have to show up on the element, so I think this is just an unfortunate requirement.
