### ISSUE TITLE
Polyfill features needed for supported older browsers

### ISSUE THREAD

**Issue by hopkins-tk** [webcomponents/shadycss#29]
`Object.assign` is needed for proper working in supported versions of **InternetExplorer**.

```
Object doesn't support property or method 'assign'
```

See: https://github.com/webcomponents/shadycss/search?utf8=%E2%9C%93&q=Object.assign

**Comment by ebidel** [comment]
Babel has a plugin for this: https://babeljs.io/docs/plugins/transform-object-assign/

We can use that when transpiling the code.

**Comment by Hotell** [comment]
not everyone is using babel @ebidel :)  You should state that explicitly in docs what "native" es6 features user has to polyfill.

**Comment by SerkanSipahi** [comment]
@ebidel @Hotell i think babel is using core-js (transform-object-assign, ..., ..., and more)

**Comment by azakus** [comment]
I've marked `Object.assign`, and a few other ES6 goodies, as requirements for the Polyfill here: https://github.com/webcomponents/shadycss/commit/1842e4bdf3b9e87f98d7e2a5ccf93a278ce985e3

Adding ES6 polyfills to each polyfill that needs them is a penalty for users who need multiple polyfills.
