### ISSUE TITLE
Implement dynamic scoping

### ISSUE THREAD

**Issue by sorvell** [webcomponents/shadycss#3]
ShadyCSS adds scoping classes to dom in order to limit application of styles to simulated shadowRoots. Currently, this api is limited to templates that are decorated and then stamped into simulated shadowRoots. It should be able to react to dom mutations and keep this scoping up to date. It probably makes sense to use a deep MutationObserver do to this.

**Comment by kevinSuttle** [comment]
See also: https://github.com/w3c/csswg-drafts/issues/270

**Comment by blasten** [comment]
Also, consider when the styles are reset via bindings:

```html
<dom-module id="x-foo">
  <template>
    <style>
      :host {
        display: block;
      }

      .red {
        color: red;
      }
    </style>
    <div class$="red [[customStyle]]">Red</div>
  </template>
  <script>
    Polymer({
      is: 'x-foo',
      properties: {
        customStyle: {
          type: String,
          value: ''
        }
      }
    });
  </script>
</dom-module>
<x-foo></x-foo>
```

**Comment by sorvell** [comment]
Fixed via https://github.com/webcomponents/shadycss/pull/25.
