### ISSUE TITLE
shadyCss breaks "class" attribute in IE 11 

### ISSUE THREAD

**Issue by Hotell** [webcomponents/shadycss#36]
When shadyCss is loaded ( not used ) it breaks `class` attribute on elements  ( used with SkateJS )

full description:

https://github.com/skatejs/skatejs/issues/950

**Comment by azakus** [comment]
I think this might be #28, where ShadyCSS modifies the classList for scoping. It's not really something I can avoid, as I mention here: https://github.com/webcomponents/shadycss/issues/28#issuecomment-331584798
