### ISSUE TITLE
Provide an `applyStyle` api that never recurses into an element's dom

### ISSUE THREAD

**Issue by sorvell** [webcomponents/shadycss#42]
It's typical to call `applyStyle` when a custom element is connected to dom. However, when this is done, any of its shadowRoot children are also connected. Therefore if `applyStyle` recurses into these children and then is called again when these children's connectedCallback fires, this will be O(n^2). Instead a version of `applyStyle` that never recurses should be used when an element is connected. Note, this is especially bad when custom properties are shimmed because the work is non-trivial.

**Comment by azakus** [comment]
Fixed by #53
