### ISSUE TITLE
CSS for elements is exchange.

### ISSUE THREAD

**Issue by lukasoppermann** [webcomponents/shadycss#43]
Hey,

so I have two custom elements, one is nested inside the other. 

In Firefox it works fine, however in chrome the css of the elements are mixed up. So the outer element has the css of the inner element, etc.

Am I doing something wrong. I have not tested chrome without the polyfill. Is there a best practise on how to build a web component that works with and without the polyfill (thinking of the missing ShadyCSS element without the polyfill)?

Please let me know what more info you need. Also I will try to get the example up as soon as possible.

**Comment by SerkanSipahi** [comment]
@lukasoppermann im not an expert but i think its better if you share your code.
