### ISSUE TITLE
Factor library so that less code is needed when native shadow dom is available

### ISSUE THREAD

**Issue by sorvell** [webcomponents/shadycss#46]
Currently this library provides (1) a style scoping mechanism mean to provide styling like native shadow dom, (2) a css custom properties shim, (3) a css @apply shim that works with native custom properties, (4) a custom-style element that supports these features outside of shadow dom.

Browsers like Chrome and Safari 10.2 that have native shadow dom and css custom properties still need feature (3) @apply shimming. Ideally, this library would be factored so that these browsers can load a build that provides only this functionality.

**Comment by azakus** [comment]
Currently being implemented in https://github.com/webcomponents/shadycss/tree/closure-compat, 
new repo for Apply-shim has been created at https://github.com/webcomponents/apply-shim
