### ISSUE TITLE
IE 11 template.content support

### ISSUE THREAD

**Issue by josevimlet** [webcomponents/shadycss#51]
I've been testing ShadyCSS with all major browsers and found that **prepareTemplate** fails on IE11 
Currently I'm using https://github.com/skatejs/web-components that includes ShadyCSS, and when I call 

`ShadyCSS.prepareTemplate(template, "my-element"); on IE11
 `

the console shows an error saying it **cant call querySelector of null**. 

After some research I can see that template exist but lacks the content property shouldn't this be covered by the polyfill?

**Comment by valdrinkoshi** [comment]
ShadyCSS assumes the browser supports template. If it doesn't, you should load the polyfill, e.g. in webcomponentsjs we use https://github.com/webcomponents/template

**Comment by josevimlet** [comment]
Nice, I've just tested it and all is working now many thanks @valdrinkoshi

**Comment by azakus** [comment]
Looks like you have a workaround, closing.
