### ISSUE TITLE
Edge/IE11: "Unable to get property 'cssText' of undefined or null reference" when HTML Import includes <link rel="stylesheet">

### ISSUE THREAD

**Issue by keanulee** [webcomponents/shadycss#57]
For example, when trying to include font-roboto (or any paper-styles import that includes font-roboto):

```html
<link rel="import" href="../../font-roboto/roboto.html">
```

cc @azakus @frankiefu

**Comment by azakus** [comment]
Looks like this is a particular combination of HTMLImports polyfill and a bug in handling empty style elements.

**Comment by valdrinkoshi** [comment]
In Edge/IE11 HTMLImports puts a placeholder element in place of the stlyes/links when it finds a `<link rel=stylesheet>`, and moves the originals to `<head>`. You can access to the original from the placeholder element through `el.__appliedElement`
https://github.com/webcomponents/html-imports#imported-stylesheets-in-ieedge

**Comment by azakus** [comment]
Yeah, I wasn't tracking that element correctly for custom-styles 👎
