### ISSUE TITLE
CSS @apply not working when parent has same component as sibling

### ISSUE THREAD

**Issue by azakus** [webcomponents/shadycss#69]
_From @jehna on March 10, 2017 12:52_

### Description
`@apply`'ed CSS property from native CSS mixin is not getting applied on component, when the component has been used previously in the DOM without the CSS property.

#### Live Demo
http://jsbin.com/hiceguvoca/1/edit?html,console,output

#### Steps to Reproduce
1. Create `my-element`
2. Append `my-element` to document.body
3. Create `wrapper-element` that also has `my-element` inside it.
4. Append `wrapper-element` to body after `my-element`
5. `@apply` a css variable called `--css-variable` in `my-element`
6. Try to set any CSS property to the `--css-variable` block inside the `wrapper-element`

#### Expected Results
The CSS property should be applied to the `my-element` component inside `wrapper-element`

#### Actual Results
The CSS property is not applied.

### Browsers Affected
- [x] Chrome
- [ ] Firefox
- [ ] Edge
- [ ] Safari 9
- [ ] Safari 8
- [ ] IE 11

### Versions
- Polymer: 2.0-preview
- webcomponents: v1

_Copied from original issue: Polymer/polymer#4410_

**Comment by azakus** [comment]
_From @jehna on March 10, 2017 12:55_

## Known workaround:

Add the same CSS property to the component that was first introduced in the DOM. (see comment in the jsbin example)

**Comment by azakus** [comment]
Can reproduce without Polymer, so this is probably a ShadyCSS bug: http://jsbin.com/medaday/edit?html,output

**Comment by jehna** [comment]
@azakus The `@apply` seems to not work at all in your example, even with the workaround.

**Comment by azakus** [comment]
Ha sorry, I had forgetten that Polymer loads the `@apply` library.

**Comment by jehna** [comment]
Now the sample seems to work fine. Is this a Polymer issue after all?

**Comment by jehna** [comment]
@azakus any update on this?

**Comment by TomK** [comment]
@azakus we are also having this problem.
It is not solely where the element is used higher in the dom, for us it is occurs with a common ancestor.
The same "workaround" fixes our problem, but it really is horrible and very difficult to track down.  In our case the bug occurs using `paper-input` mixins.

See the following simplified example: http://codepen.io/oridan/pen/jBQodm

two elements, both using paper-input, both with the same mixin defined.  Removing the definition from the first element breaks the apply in both of them.

**Comment by TomK** [comment]
Updated my codepen.
ele1 should have red text
ele2 should have green background

**Output:**
![image](https://cloud.githubusercontent.com/assets/299656/24548013/cbeeb0c2-160a-11e7-9d9a-9498c09327f5.png)

**Comment by freshp86** [comment]
FYI, I posted a potential fix at https://github.com/Polymer/polymer/issues/4486#issuecomment-290945135. Not sure if that bug is identical with this one. Worth checking if the candidate fix is addressing this one too.

**Comment by azakus** [comment]
Looks like this is a bug in the updating instances with the Apply Shim.

If you force ShadyDOM to be enabled, this works as expected: http://jsbin.com/diyopa/2/edit?html,output

**Comment by azakus** [comment]
You are right @freshp86, this does appear to be a Polymer bug. The equivalent raw custom-elements + apply-shim example works as expected: http://jsbin.com/qexuyoy/edit?html,output

**Comment by azakus** [comment]
Given that this a Polymer issue, I'll close this and reopen the original Polymer issue. Sorry for the churn!
