### ISSUE TITLE
IE Edge inline style variable get ignored

### ISSUE THREAD

**Issue by daKmoR** [webcomponents/shadycss#72]
hey,

using latest
- polymer
- shadycss
release candidate

if you style something with
```html
    <picture-frame style="--border: 5px solid red;">
      <img src="https://www.polymer-project.org/images/logos/p-logo-32.png">
    </picture-frame>
```

the --border variable get's ignored in IE Edge. Variables defined within a `<custom-style>` do have affect as expected.

See Example in Chrome and IE Edge.
http://plnkr.co/edit/cSIs0ODeyUsaXiemxhyP?p=preview

**Comment by azakus** [comment]
The CSS Custom Property shim doesn't support inline styling, which is why this doesn't work in IE or Edge.

I'll update the docs to show that this is unsupported.

**Comment by daKmoR** [comment]
too bad but I now know why it's not supported... IE and Edge won't allow you to access "unsupported" css properties... even a `element.getAttribute('style')` will not contain even the string of the CSS Custom Properties...

My Elements are part of a cms and there you can define options... so for every element the user should be able to modify the Custom Properties... (e.g. style the element as needed)

IE11 Support was required so I used a little workaround...

1) While creating the inline styles in the CMS I copy them to `data-styles`
2) data-styles will be untouched by IE/Edge so I can use it to do updateStyles with ShadyCSS

For my projects I do have a universal BaseClass so I added the functionality there but it could be easily transferred to a "Behavior/Mixin"... And then we/I could create a guide to a possible workaround for anyone who needs it?

this is my current code (which would probably need some cleanup for a guide...) 
But if the approach would be viable just let me know and I would prepare more...

```html
<my-element style="--my-border: 5px solid red;" data-style="--my-border: 5px solid red;">
	The Example Element that will support inline css custom property even for ie11
	It extends from BaseElement
</my-element>

<script>

	class BaseElement extends Polymer.Element {

		ready() {
			super.ready();
			this.updateStyles({});
		}

		updateStyles(styles) {
			if (styles === undefined) {
				return;
			}
			let newStyle = styles;
			let currentStyleString = this.getAttribute('style') || this.getAttribute('data-style');
			if (currentStyleString !== undefined && currentStyleString !== null && currentStyleString !== '') {
				newStyle = {};
				let currentStylesPairs = currentStyleString.split(';');
				for (let currentStylePairKey in currentStylesPairs) {
					if (currentStylesPairs.hasOwnProperty(currentStylePairKey)) {
						let currentStylePairString = currentStylesPairs[currentStylePairKey];
						if (currentStylePairString !== '') {
							let currentStylePair = currentStylePairString.split(':');
							if (currentStylePair.length === 2) {
								newStyle[currentStylePair[0]] = currentStylePair[1];
							}
						}
					}
				}

				for (var newStylePairKey in styles) {
					if (styles.hasOwnProperty(newStylePairKey)) {
						newStyle[newStylePairKey] = styles[newStylePairKey];
					}
				}
			}

			if (window.ShadyCSS && window.ShadyCSS.nativeCss === true) {
				var newStyleString = '';
				for (var key in newStyle) {
					if (newStyle.hasOwnProperty(key)) {
						newStyleString += key + ': ' + newStyle[key] + ';';
					}
				}
				this.setAttribute('style', newStyleString);
			} else {
				ShadyCSS.styleSubtree(this, newStyle);
			}
		}

	}

</script>
```

**Comment by daKmoR** [comment]
I just published a behavior that can be used to support inline css custom properties even for for IE11.

if you need this feature you should take a look :)

https://www.webcomponents.org/element/daKmoR/grain-update-inline-style-behavior

**Comment by azakus** [comment]
Yeah, still have no desire to support inline styling like this. Super costly from the polyfill's perspective.
