### ISSUE TITLE
No getComputedStyleValue on Polymer.Element?

### ISSUE THREAD

**Issue by kevinpschaaf** [webcomponents/shadycss#83]
_From @arthurevans on March 4, 2017 2:54_

I suspect it's used significantly less frequently that `updateStyles()`, but it seemed kind of funky to me that we had a facade for `updateStyles` on `Polymer.Element`, but not for `getComputedStyleValue`. 

Currently documented solution for this is:

```
if (ShadyCSS) {
  style = ShadyCSS.getComputedStyleValue('--something');
} else {
  style = getComputedStyle(this, '--something');
}
```
Which hopefully I got right. If not, it's here:

https://github.com/Polymer/docs/blame/master/app/2.0/docs/devguide/custom-css-properties.md#L361

_Copied from original issue: Polymer/polymer#4374_

**Comment by kevinpschaaf** [comment]
At one point we discussed patching `getComputedStyleValue` to make the custom property handling in the shim transparent... @azakus ?

**Comment by kevinpschaaf** [comment]
The plan of record will be for `shadycss` to patch `window.getComputedStyle()` to have the return object's `getPropertyValue()` to return the correct value for custom properties.

Note the correct incantation is the following (note the native syntax in the else clause is what we would shim to work transparently; the syntax is a bit ugly but that's the native API):

```
if (window.ShadyCSS) {
  style = ShadyCSS.getComputedStyleValue(el, '--something');
} else {
  style = getComputedStyle(el).getPropertyValue('--something');
}
```

**Comment by jimivdw** [comment]
Not sure if I should create a separate issue for this, but it appears that it is also no longer possible to retrieve the value of a CSS mixin using `getComputedStyleValue`, which was possible before. Is this intended? And is there a different way of retrieving mixin values now?

**Comment by azakus** [comment]
@jimivdw that was never supported, and is actually really hard to do with the ApplyShim, as the original `--mixin` variable is _long_ gone by the time you would try to get the value for it.

**Comment by azakus** [comment]
Closing this issue. Polymer has `getComputedStyleValue` on the Polymer 1.x hybrid elements.
