### ISSUE TITLE
Text-align from CSS variable doesn't work on Edge

### ISSUE THREAD

**Issue by jehna** [webcomponents/shadycss#88]
# Description

Setting CSS `text-align` property from a CSS variable does not work on Edge browser.

## How to reproduce

1. Clone the following project: https://github.com/jehna/polymer-css-text-align-edge-bug
2. Install dependencies & build the project
3. Open site in latest Edge browser (currently version 15)

### Behaviour

The bottom div isn't aligned with `text-align: center;`

![screen shot 2017-04-19 at 15 51 46](https://cloud.githubusercontent.com/assets/2676795/25180826/2b18a122-2518-11e7-84b5-3dbd98a00b0c.png)

### Expected behaviour

The bottom div's text should be centered:

![screen shot 2017-04-19 at 15 52 42](https://cloud.githubusercontent.com/assets/2676795/25180865/3d576508-2518-11e7-9b70-93416b170294.png)

## Browsers

- [x] Microsoft edge 15
- [x] Microsoft Edge 14 (see issue #87)
- [ ] Chrome
- [ ] Firefox
- [ ] Safari

**Comment by azakus** [comment]
This looks like an Edge bug. In a reproduction with no Polymer or ShadyCSS involved, this works on Chrome, Firefox, and Safari, but fails in Edge 15: http://jsbin.com/gutaki/edit?html,output

**Comment by jehna** [comment]
Opened an issue to Edge's issue tracker:

https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/11728214/

Closing the this issue for now.
