### ISSUE TITLE
invalid-meta in bower.json, The "main" field cannot contain minified files

### ISSUE THREAD

**Issue by lawrence9811** [webcomponents/shadycss#89]
When running polymer init and using the polymer-2-application template, there's some warning in related to shadycss component during installation:

bower shadycss#^v1.0.0-rc.1                        invalid-meta for:C:\Users\Lawrence\AppData\Local\Temp\DESKTOP-XXXXXXX-Lawrence\bower\xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-2388-v2Cifq\bower.json
bower shadycss#^v1.0.0-rc.1                        invalid-meta The "main" field cannot contain minified files

**Comment by TimvdLippe** [comment]
This is working as intended, as the polyfill should only be loaded as minified file, as it is the bundle of all development files. We do not want to expose the development files in the final build.
