### ISSUE TITLE
Investigate a more automatic API

### ISSUE THREAD

**Issue by azakus** [webcomponents/shadycss#90]
- Could `document.querySelectorAll` for styles to add to CustomStyleInterface on boot, instead of requiring manual intervention.

- Styling a template could be tricky without `ShadyCSS.prepareTemplate`, but it bears some investigation.

- Accept strings for `ShadyCSS.prepareTemplate` that can become `<template>` maybe?

**Comment by azakus** [comment]
@robdodson

**Comment by robdodson** [comment]
❤️

**Comment by azakus** [comment]
Deduplicated against #134
