### ISSUE TITLE
`inherit` within `@apply` definitions gets overriden by User-Agent styles

### ISSUE THREAD

**Issue by nazar-pc** [webcomponents/shadycss#91]
### Description
`inherit` within `@apply` definitions gets overriden by User-Agent styles, which didn't happen in Polymer 1.x with full WebComponents v0 polyfill (and without it in Chromium), but now happens in Polymer 2.0 and WebCmponents v1 lite.

#### Live Demo
https://jsbin.com/guwinowudo/edit?html,output

#### Steps to Reproduce
1. Define `@apply` definition with `font-family` set to `inherit`
2. Speficy non-default `font-family` for `body`
3. Use `@apply` rule in element in `::slotted(button)`

#### Expected Results
`inherit` effectively applies `body`'s `font-family`

#### Actual Results
User-Agent's `font-family` has higher specificity, actual `font-family` is shown as `apply-shim-inherit` in Dev Tools in both tested browsers.

### Browsers Affected
Only tested in these:
- [x] Chromium nightly
- [x] Firefox

### Versions
Polymer: 2.0-preview

**Comment by nazar-pc** [comment]
@azakus, this is a major bug for me, especially considering 1.0.0 being just released.
Can you take a look at this and assign a priority at least?

**Comment by nazar-pc** [comment]
@sorvell, can you as the author of the first commit introducing https://github.com/webcomponents/shadycss/blob/b9710673cbccc54a32eb322d27c4f8688c186da9/src/apply-shim.js#L321-L326 explain what is going on and why? Comment doesn't tell me anything useful.

Native `@apply` implementation in Chromium works fine, but when including `apply-shim` on the page it breaks.

**Comment by nazar-pc** [comment]
Related to https://github.com/Polymer/polymer/issues/4282, originated from https://github.com/Polymer/polymer/pull/3824 and sadly `_replaceInitialOrInherit` is not covered by any tests, I can just remove contents of the function and all the tests are fine:(

**Comment by nazar-pc** [comment]
Ping here, almost 3 months my fonts are broken because of this

**Comment by nazar-pc** [comment]
@sorvell , can you take a look at this any time soon?

**Comment by azakus** [comment]
This looks like the same issue as http://crbug.com/888965

**Comment by azakus** [comment]
@nazar-pc I apologize for the delay on handling this issue.

The deprecation of `@apply` as a specification has left the ApplyShim in a deprecated, critical maintenance only state, and I haven't been keeping a good track of these issues.
